### PR TITLE
Feathers v3 core (Buzzard)

### LINKED ISSUE #216: Mounted apps should register their services at the parent level
Once we do this:

```
// api.js
module.exports = feathers().use('/todos', todoService);

// app.js
var main = feathers();
var api = require('./api');

main.use('/api', api);
```

Will you lookup your todos service by doing `app.service('/api/todos')`?

### LINKED ISSUE #232: Mounted sub-apps should hook into their parents setup
Initially brought up in https://github.com/feathersjs/feathers-authentication/issues/72, sub-apps will hook into their parent `setup` (so that you don't have to call a sub-apps `setup` manually) only when a real-time provider is configured. This should however always be the case.

Since it may cause odd errors (with `app.setup` being run twice) the best way is probably to change this in v3.

### LINKED ISSUE #258: Make Feathers server framework independent to work with Express, Koa and Hapi
Now that Feathers works library independent on the client already (see https://github.com/feathersjs/feathers/pull/193), we don't really need Express as hard dependency for the server anymore either. Instead, we can create separate modules for Express, Koa and potentially Hapi that can be configured just like any other plugin:
## Express

The only thing to change upgrading from a Feathers 2 application would be to `app.configure(express())`:

``` js
const feathers = require('feathers');
const express = require('feathers-express');

const app = feathers()
  // Make this app Express compatible
  .configure(express())
  // Configure REST API that uses Express
  .configure(express.rest());

// Use any Express middleware
app.use(bodyParser.json());
// Use Feathers services normally
app.use('/todos', {
  get(id) {
    return Promise.resolve({ id, description: `You have to do ${id}!` });
  }
});
```
## Koa

Koa support came up several times (see #83 and #58). This can now be done very similar:

``` js
const feathers = require('feathers');
const koa = require('feathers-koa');

const app = feathers()
  // Make this app Koa compatible
  .configure(koa())
  // Configure Koa REST handler
  .configure(koa.rest());

// Use normal Koa middleware
app.use(function *(){
  this.body = 'Hello World';
});

// Use a Feathers service through app.service
app.service('/todos', {
  get(id) {
    return Promise.resolve({ id, description: `You have to do ${id}!` });
  }
});
```

### LINKED ISSUE #376: Hooks do not apply for realtime events
Hi,
I've just found that hooks do not apply for realtime events. Following code will remove password field from service response.

`app.service('users').after({
    all: hooks.remove('password'),
});`

But when entry is updated, whole entry is emmited through updated event, even with password field.

Are there any plans for unifiying filters for both service methods and realtime events or is there any workaround?

### LINKED ISSUE #388: Event channels/rooms
In many cases, service events need to be filtered to restrict their emission to a limited set of clients (1 to 1 or 1 to few users messages in a chat app for example). Filters allow to do this but at the cost of iterating through all connections, for each event... This can cause unnecessary server load when the number of events and/or connected clients is important.
One nice feature that could be considered to improve this would be to add some possibility to provide a list of connections to be considered by the dispatcher along with the service event. That way, the foreach loop (io.sockets.clients().forEach(function(socket) {...} ) could be performed only on this restricted list of connections (and on all connections by default, like already the case). Alternatively we could also pass a list of user _ids and keep a mapping of _id to connection automatically somewhere in feathers.
With this improvement, it would be possible, for example, to maintain a list of user._id <-> connection (if not handled by feathers) and to simply call the dispatcher to emit an event (like a 1 to 1 message) on a specific connection (retrieved directly from the user._id -> connection hash table, which is much quicker than having to iterate through all connections (with filters) to find the targeted one)

To give you an idea, I made a really simple benchmark to test the difference between making each time a really simple test (like connection.user._id === message.to_user_id) compared to looking for a given entry into a connection hash table :

Here are the results:

with 10k connections:
foreach method: 3.608ms
hash method: 0.073ms

with 100k connections:
foreach method: 27.761ms
hash method: 0.126ms

with 1M connections:
foreach method: 284.016ms
hash method: 0.288ms

So,, until 10k connections, the difference is still "reasonable". But passed this, the difference start to be significant (pretty much 1/3 second just to loop through connections in the dispatcher, for a single event, when 1M users. Meaning you wouldn't be able to treat more than 3 events/s (at best case) when 1M concurrent users whereas you could treat 1000x more if you knew the connection where to dispatch a priori). 
And you have to keep in mind that number of events per second generally grows with number of users...
So the foreach loop in the dispatcher can became a real bottleneck if you want to use feathers for big apps... (If you have 1M concurent users, you wouldn't be able to treat more than 3 event/second on each node because of this) 

Here is the code used for my really simple benchmark:

```
var nbconnections = 1000000;

var array = new Array(nbconnections);
console.time("foreach method");
array.forEach(function(socket) {
    if (socket === 0){

    }
});
console.timeEnd("foreach method");


var hash = {};
for (i = 0; i < nbconnections; i++) {
    hash[i+'']=i;
}
console.time("hash method");
var conn = hash['1000'];
console.timeEnd("hash method");
```

### LINKED ISSUE #394: sub apps - possible losing callback of socket.io event in sub apps
I want to implement versioning for socket.io API based on sub apps. So I just triggered sub app io item to go to the version based namespace (v1, v2). I get this worked with events but services and ack callbacks failed to be called.

I am using messages app from the example.

I have an issue when ack doesn't called on client connected through socket.io. Looks like server couldn't interpret event and call appropriate service.
This issue is applied only on sub apps, when I move the same sub app to be the main app the callbacks became working.

my setup

app v2

```

app.configure(configuration(path.join(__dirname, '../..')));

app.use(compress())
  .options('*', cors())
  .use(cors())
  .use(favicon( path.join(app.get('public'), 'favicon.ico') ))
  .use('/', serveStatic( app.get('public') ))
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(hooks())
  .configure(rest())
  .configure(socketio(function(io) {
    //io.of('v2')   // uncommented when using as sub app
   // io = io.of('v2) // I tried this too
  }))
  .configure(services)
  .configure(middleware);

module.exports = app;
```

main app (this is how I make app2 be the main one and get callbacks works)

```
const v2app = require('./v2/app');

/*
const app = feathers()

app.configure(configuration(path.join(__dirname, '..')))
  .use('/v2', v2app)
  .use(favicon( path.join(app.get('public'), 'favicon.ico') ))
  .use('/', serveStatic(app.get('public')));
*/
module.exports = v2app;
```

I am using sample code to emit an event from browser

```
  var host = 'http://localhost:8080';
      var socket = io(host, {
        transport: ['websockets']
    });
 socket.emit('messages::create', {
                "text": "I really have to iron"
            }, (error, message) => {
             console.log('Todo created', message);
            });
```

normal log for emit 'messages:create'

```
  engine:ws received "425["messages::create",{"text":"I really have to iron"}]" +21s
  engine:socket packet +0ms
  socket.io-parser decoded 25["messages::create",{"text":"I really have to iron"}] as {"type":2,"nsp":"/","id":5,"data":["messages::create",{"text":"I really have to iron"}]} +1ms
  socket.io:socket got packet {"type":2,"nsp":"/","id":5,"data":["messages::create",{"text":"I really have to iron"}]} +0ms
  socket.io:socket emitting event ["messages::create",{"text":"I really have to iron"}] +0ms
  socket.io:socket attaching ack callback to event +0ms
  feathers-socket-commons:methods Got 'messages::create' event with connection +0ms { provider: 'socketio',
  req: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     socket: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 865,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1469,
        parser: null,
        on: [Function: socketOnWrap],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: null,
        _peername: [Object],
        _called: true },
     connection: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 865,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1469,
        parser: null,
        on: [Function: socketOnWrap],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: null,
        _peername: [Object],
        _called: true },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { host: 'localhost:8080',
        connection: 'keep-alive',
        origin: 'null',
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.117 Safari/537.36 Vivaldi/1.3.551.30',
        accept: '*/*',
        'accept-encoding': 'gzip, deflate, sdch',
        'accept-language': 'en-US,en;q=0.8',
        cookie: 'io=KaoO_PJSzouCsPmiAAAK' },
     rawHeaders: 
      [ 'Host',
        'localhost:8080',
        'Connection',
        'keep-alive',
        'Origin',
        'null',
        'User-Agent',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.117 Safari/537.36 Vivaldi/1.3.551.30',
        'Accept',
        '*/*',
        'Accept-Encoding',
        'gzip, deflate, sdch',
        'Accept-Language',
        'en-US,en;q=0.8',
        'Cookie',
        'io=KaoO_PJSzouCsPmiAAAK' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '/socket.io/?EIO=3&transport=polling&t=LQZQcdR',
     method: 'GET',
     statusCode: null,
     statusMessage: null,
     client: 
      Socket {
        _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: true,
        destroyed: true,
        bytesRead: 0,
        _bytesDispatched: 865,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 1469,
        parser: null,
        on: [Function: socketOnWrap],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: null,
        _peername: [Object],
        _called: true },
     _consuming: true,
     _dumped: true,
     _query: { EIO: '3', transport: 'polling', t: 'LQZQcdR' },
     res: 
      ServerResponse {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedHeader: {},
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: null,
        connection: null,
        _header: 'HTTP/1.1 200 OK\r\nContent-Type: application/octet-stream\r\nContent-Length: 101\r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Allow-Origin: null\r\nSet-Cookie: io=cSbMtdP2FZsJhmn7AAAA\r\nDate: Fri, 19 Aug 2016 15:27:55 GMT\r\nConnection: keep-alive\r\n\r\n',
        _headers: null,
        _headerNames: {},
        _onPendingData: [Function: updateOutgoingData],
        statusMessage: 'OK',
        statusCode: 200 },
     cleanup: [Function: cleanup],
     read: [Function] } }
  socket.io:socket sending ack [null,{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}] +4ms
  socket.io:client writing packet {"id":5,"type":3,"data":[null,{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}],"nsp":"/"} +0ms
  socket.io-parser encoding packet {"id":5,"type":3,"data":[null,{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}],"nsp":"/"} +0ms
  socket.io-parser encoded {"id":5,"type":3,"data":[null,{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}],"nsp":"/"} as 35[null,{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}] +0ms
  engine:socket sending packet "message" (35[null,{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}]) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "435[null,{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}]" +0ms
  feathers-socket-commons:events Dispatching messages created with data +0ms { text: 'I really have to iron', _id: 'OTORLYUzQsaZSxQT' }
  socket.io:client writing packet {"type":2,"data":["messages created",{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}],"nsp":"/"} +1ms
  socket.io-parser encoding packet {"type":2,"data":["messages created",{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}],"nsp":"/"} +0ms
  socket.io-parser encoded {"type":2,"data":["messages created",{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}],"nsp":"/"} as 2["messages created",{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}] +0ms
  engine:socket sending packet "message" (2["messages created",{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}]) +0ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "42["messages created",{"text":"I really have to iron","_id":"OTORLYUzQsaZSxQT"}]" +0ms
  engine:ws received "2" +4s
  engine:socket packet +0ms

```

when sub app v2 added as sub app 

```
 var host = 'http://localhost:8080/v2';
      var socket = io(host, {
        transport: ['websockets']
    });
 socket.emit('messages::create', {
                "text": "I really have to iron"
            }, (error, message) => {
               console.log('Todo created', message);
            });
```

```
    engine:ws received "42/v2,0["messages::create",{"text":"I really have to iron"}]" +6s
  engine:socket packet +0ms
  socket.io-parser decoded 2/v2,0["messages::create",{"text":"I really have to iron"}] as {"type":2,"nsp":"/v2","id":0,"data":["messages::create",{"text":"I really have to iron"}]} +0ms
  socket.io:socket got packet {"type":2,"nsp":"/v2","id":0,"data":["messages::create",{"text":"I really have to iron"}]} +0ms
  socket.io:socket emitting event ["messages::create",{"text":"I really have to iron"}] +1ms
  socket.io:socket attaching ack callback to event +0ms
  engine:ws received "42/v2,1["messages::create",{"text":"I really have to iron"}]" +0ms
  engine:socket packet +0ms
  socket.io-parser decoded 2/v2,1["messages::create",{"text":"I really have to iron"}] as {"type":2,"nsp":"/v2","id":1,"data":["messages::create",{"text":"I really have to iron"}]} +1ms
  socket.io:socket got packet {"type":2,"nsp":"/v2","id":1,"data":["messages::create",{"text":"I really have to iron"}]} +0ms
  socket.io:socket emitting event ["messages::create",{"text":"I really have to iron"}] +0ms
  socket.io:socket attaching ack callback to event +0ms
```

### LINKED ISSUE #408: Make feathers-hooks part of core and service events a hook
The [feathers-hooks](https://github.com/feathersjs/feathers-hooks) plugin has become such an essential part of Feathers that it should probably become a core dependency. A good time to implement this is when removing callback support in both, hooks and services in Feathers v3.

This would also allow us to improve the [service event dispatching](https://docs.feathersjs.com/real-time/events.html) by turning it into a hook (that always runs last) instead of a separate mixin (where the same functionality is currently provided by a different dependency [Rubberduck](https://github.com/daffl/rubberduck)).

Related issues:
- #405 and #406 are related to this but not completely solve the problem because the `hook` object in a service event is not the same as during the method call (which it should be).
- #376 can also be solved with this since it would then allow us to set the data that need to be dispatched in the hook
- Also addresses #388 (specifically https://github.com/feathersjs/feathers/issues/388#issuecomment-239564856) since you can set the dispatch data already in the hook which also allows to simplify and make event filtering more performant.

### LINKED ISSUE #515: Universal/Isomorphic Express
I just wanted to point you guys to a discussion happening in the Express project that, in a roundabout way, was actually triggered in part by Feathers JS.

Feathers JS has an application object (Feathers) that mimics the Express API. I really liked that aspect of Feathers so I looked how you did it and it inspired me to try to take it a step further, by also enabling the `use` method to work on the client... I ended up building [uexpress](https://github.com/download/uexpress). 

I asked [a question](https://github.com/expressjs/express/issues/3198) about the Express source code on their issue tracker and it was seen by Wesley Todd, who, with his project [nighthawk](https://github.com/wesleytodd/nighthawk), was doing something similar. He somehow got it scheduled on an [Express TC meeting](https://github.com/expressjs/discussions/issues/51) and they [discussed](http://youtu.be/Ol-gr_OQuHg) what it would take in the core of Express 5 to allow projects like nighthawk, uexpress and Feathers JS to assemble their own Express-compatible servers, using the same parts used by Express core (factored out into separate packages).

Since you guys have a lot of experience in writing isomorphic code with Express, and are (as I understand it) looking at generalizing this concept over to multiple server types (Koa, etc), I think you would be able to weigh in on this discussion with your insights.

### LINKED ISSUE #521: Consider redesigning the Socket provider event format to move service and method into the payload.
When you call, from the feathers client, a non-existent service, or a non-existent method on an existing service over the Socket provider, you end up waiting for the socket timeout.

This is because there is no cross-library way to figure out if an event is listened-to or not other than a timeout.  You can't listen to all events.

The Socket provider's events currently have the format `emit('<servicepath>::<methodname>', <data>)`

If the format was changed to something like `emit('feathers-event',{service: <servicepath>, method: <methodname>, ... })` then the server could determine if the service and method exist, and if not, callback with an error.

### LINKED ISSUE #566: Re-using services
In ref to feathers-hooks issue [#154](https://github.com/feathersjs/feathers-hooks/issues/154)

There was an issue when using a service under a different route path, ie:
```
  app.use('/projects', createService(options));

  const service = app.service('/projects');

  app.use('/me/projects', service)
```
The __hooks object was being overwritten, which has since been fixed but now in the console there is the following output:
```
express:router <anonymous>  : /projects +8ms
feathers-errors NotFound(404): Page not found +1ms
express:router <anonymous>  : /projects +0ms
finalhandler default 404 +1ms
finalhandler cannot 404 after headers sent +0ms
Error: Can't set headers after they are sent.
  at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
  at ServerResponse.header
....
```

It seems as though it is trying to route it again and not finding the route and trying to throw NotFound error but a response has already been set with headers. 

As per @daffl suggestion to post this in here.

Thanks

### LINKED ISSUE #588: Using Rollup throws errors about dependency Rubberduck using eval
### Steps to reproduce

- Rollup throws "Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification" - https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval
- see repo at https://bitbucket.org/colwilson/feathers-rollup-rubberduck-issue/src 
- deprecation of rubberduck is also mentioned in **Make feathers-hooks part of core and service events a hook** https://github.com/feathersjs/feathers/issues/408

```sh
$ yarn
$ yarn dev
yarn dev v0.21.3
$ cross-env NODE_ENV=development rollup -c 
preferring built-in module 'events' over local alternative at '/home/col/dev/play-valued-stud/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at '/home/col/dev/play-valued-stud/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
preferring built-in module 'events' over local alternative at '/home/col/dev/play-valued-stud/node_modules/events/events.js', pass 'preferBuiltins: false' to disable this behavior or 'preferBuiltins: true' to disable this warning
⚠️   Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval
node_modules/rubberduck/lib/rubberduck.js (33:6)
31: 
32:     if (strict) {
33:       eval('wrapped = ' + utils.addArgs(wrapped.toString(), fn.length));
          ^
34:     }

⚠️   Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval
node_modules/rubberduck/lib/rubberduck.js (76:6)
74: 
75:     if (strict) {
76:       eval('wrapped = ' + utils.addArgs(wrapped.toString(), fn.length));
          ^
77:     }

Done in 2.89s.

```

### Expected behavior
Should compile

### Actual behavior
rollup fails with "Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification" - https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval

### LINKED ISSUE #589: hook.path is not set in filter function
### Steps to reproduce

```
app.service('example').filter(function (data, connection, hook) {
  if (hook.path !== 'example')
    throw new Error(`hook.path is ${hook.path}`)
  return data;
})
```

### Expected behavior
`hook.path` should be set (to `'example'` in the above example), therefore the filter above should not throw an error.

### Actual behavior
`hook.path` is `undefined`, so the above filter throws an error.

### System configuration

Tested with feathers version 2.1.3.

### LINKED ISSUE #653: Application-level error hook responses inconsistent across transports
### Steps to reproduce

Add the following hook to the end of your feathers application (and force all responses to be JSON):

```js
const app = feathers();

app.use(error({html: false})); // force JSON responses for the HTTP transport

app.hooks({
  error(hook) {
    Object.assign(hook.error, {
      errors: { // override a property within the conventional shape of a feathers errors object
         foo: 'bar'
      },
      _error: 'bazzz' // add a new property
    });
    return Promise.resolve(hook);
  }
});
```

Then, call a service method that will throw an error.

Over the HTTP transport, the observed response body is:

```js
{
  "name": "BadRequest",
  "message": "Validation Error",
  "code": 400,
  "className": "bad-request",
  "errors": {
    "foo": "bar"
  }
}
```

screen shot 2017-08-19 at 6 39 51 pm

The `_error` property is missing. (`errors` is overridden as expected).

Over the websocket transport, the response is:

```js
{
  className: "bad-request",
  code: 400,
  errors: {foo: "bar"},
  message: "Validation Error",
  name: "BadRequest",
  stack: "<really long string>",
  type: "FeathersError",
  _error: "bazzz"
}
```

screen shot 2017-08-19 at 6 40 11 pm

All mutations are present in the websockets response. :+1:

### Expected behavior

When you mutate `hook.error`, you should observe the same mutations across all transports.

### Actual behavior

The HTTP transport is missing some mutations.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): `feathers@2.2.1`; `feathers-errors@2.9.1`.
**NodeJS version**: 6.0.0
**Module Loader**: Webpack

### LINKED ISSUE #670: Nested Routes
Hi,
I have 2 services, Users and Addresses. I tried doing the Nested route example as in:
https://docs.feathersjs.com/faq/readme.html#how-do-i-do-nested-or-custom-routes

this results in:
/users/:userId/addresses

When a Users has only 1 address, it works. When the user has multiple addresses, I receive an error:
localhost didn’t send any data.
ERR_EMPTY_RESPONSE

However, if I do:
/addresses/?userID=xxxx
It works as expected for both single and multiple addresses.

All services are using sequelize/mysql.
I'm using:
"body-parser": "^1.17.2",
"compression": "^1.7.0",
"cors": "^2.8.4",
"feathers": "^2.1.7",
"feathers-authentication": "^1.2.7",
"feathers-authentication-hooks": "^0.1.4",
"feathers-authentication-jwt": "^0.3.2",
"feathers-authentication-local": "^0.4.3",
"feathers-configuration": "^0.4.1",
"feathers-errors": "^2.9.1",
"feathers-hooks": "^2.0.2",
"feathers-hooks-common": "^3.6.1",
"feathers-rest": "^1.8.0",
"feathers-sequelize": "^2.2.0",
"feathers-socketio": "^2.0.0",
"feathers-swagger": "^0.5.0",
"helmet": "^3.8.1",
"mysql2": "^1.4.0",
"sequelize": "^4.4.2",
"serve-favicon": "^2.4.3",
"skypager-service": "^5.4.0",
"winston": "^2.3.1"

### LINKED ISSUE #691: Allow different names and endpoints for services...
The CLI’s service generator for a Sequelize services adds a ‘name’ property to the options it passes to the service constructor.

```
const options = {
    name: 'items',
    Model,
    paginate
  };

  // Initialize our service with any options it requires
  app.use('/items', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('items');
```

1) However in this help page the 'name' option is never mentioned: https://docs.feathersjs.com/api/databases/sequelize.html#api . 

2) I’ve looked and stepped through the service() code and in fact it doesn’t seem to be used. Instead the leading slash is stripped off the service endpoint “/items” and into a variable location and the remaining part of the endpoint is also used as the service name.

3) I thought the changing the line like so app.use('/restaurants', createService({name: 'item', Model, paginate} ) would allow me to mount the service on any url but it turns out that throws this error at launch:

```
Cannot read property 'hooks' of undefined
    at EventEmitter.module.exports
    ...
```

### Proposed:
It would be great if the service name could actually be set by an option or argument such that a common service name and its code could be reused in multiple apps/projects and only the service's route changed.

### Use case:
A reusable service "items" provides the same CRUD implementation (fields, computed fields, custom processing etc) for an "item" but each app that requires/includes the service could have the route be specific to its type/client in that particular app (/restaurants, /groceries, /movies, /todo etc ).

### Notes:
- not sure: perhaps rename the service by doing find/replace in the services[] array as long as the service's actual route isn't ret-conned from location in turn.

- or perhaps vice versa: create service "items" first and then overwrite the endpoint with '/restaurants'. Issue #446 implies that maybe can only do in REST -   because of needing to unbind from transports. So this might not be an option.

### Related:
- This is a similar thing: using Sequelize I'm able to have an actual DB table name be different than whatever I call the JS model by modifying the generated code. But that doesn't apply to the service's options.name field

- issue #446 also talks about unregistering services after they're live but was removed from Buzzard. And I'm not looking for hot swapping, just intelligent options during setup

### PR DESCRIPTION
**Pull request by daffl**
This is the work from the `major` branch for Feathers v3.0.0 core (Buzzard).

- Makes Feathers framework independent (closes #258, closes #515, closes https://github.com/feathersjs/feathers-client/issues/137)
- Makes `feathers-hooks` part of core and event emitting a hook (closes #408, closes #376, closes #588, closes #376, closes #653)
- Removes Babel compilation and Node 4 support (#608)
- Allows to properly re-use services (closes #566, closes #670, closes #691)
- Improves sub-app handling (closes #232, closes #216, closes #394)
- Will be moved to the `@feathersjs` npm scope (#623)
- With related updated packages (`feathers-socketio`, `feathers-primus`) updated, this will also add support for event channels (closes #388, closes #589) and an improved websocket event format (closes #521)

### CODE REVIEW

**Comment by ekryski** [comment]
Checked it out locally. Looks good! :shipit:

**Comment by daffl** [comment]
A preliminary v3 upgrade guide for beta testing can be found at https://gist.github.com/daffl/e718f93acc7bfe32fd1e5aed0f8e7827

**Comment by kristianmandrup** [comment]
Awesome!!! Can't wait to try it out :) Does it work with Koa and Hapi now as well then!?

**Comment by daffl** [comment]
This release is more intended to set everything up for it but getting other HTTP frameworks to work with authentication requires some changes in the authentication modules that are not included in this release to keep the migration path easier.

**Pull request merged**
