### PR TITLE
chore: Remove src folder from .npmignore for ts packages

### PR DESCRIPTION
**Pull request by vonagam**
Any drawbacks to this? 

As i understand should not affect local development as `link` command ignores `.npmignore`.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request. Wouldn't we still want the correct line numbers and source references on errors though?

**Comment by vonagam** [comment]
Hm... Well, while you will know a line for an error in ts source file, while debugging you will not be able to see any code (nor source, nor build) and a place of a said error. So debugging is definitely harder...

Reproduce yourself:
1) Create and install a package with `"@feathersjs/transport-commons": "4.0.0-pre.3"`.
2) Run `node --inspect-brk`.
3) Run such erroneous code:
```js
const Channel = require('@feathersjs/transport-commons/lib/channels/channel/base').Channel;
const channel = new Channel();
channel.filter(33);
```

You will see that the error will have [`base.ts:55`](https://github.com/feathersjs/feathers/blob/28888a1a6bd61eac778573234e2d668488f9989e/packages/transport-commons/src/channels/channel/base.ts#L55) as a location reported, but you will not be able to see such file and without seeing you will not be able to place breakpoints or understand fully what's going on.

Unfortunately there is no way to selectively disable source maps in dev tools for `@feathersjs/*` dependencies and keep them working for your own code.

Do you have any solution for this?

Other way to go is to not ignore `src` folder. That way while debugging you will see ts source file and will be able to place breakpoints.

**Comment by daffl** [comment]
I think publishing the `src/` folder as well makes the most sense then. I guess there will be some slight overhead during startup but it would definitely be worth having the actual code references (otherwise most error messages might not be very helpful).

**Comment by vonagam** [comment]
Done.

**Pull request merged**
