### PR TITLE
feat: helper script to fail tests on unhandled rejections

### PR DESCRIPTION
**Pull request by vonagam**
Usage with mocha: `--require @feathersjs/adapter-tests/lib/rejections`.

### CODE REVIEW

**Comment by daffl** [comment]
I locked the version in KnexJS via https://github.com/feathersjs-ecosystem/feathers-knex/commit/054360d0eef04c31ec2c95d989093edea7ffe51c so it is on the latest which doesn't have the unhandled promise rejection issue. Since it really was a bug in the upstream library do you think we'll still need this? I don't think I've seen this problem anywhere else before since actual test and adapter errors should still fail normally.

**Comment by vonagam** [comment]
The problem was on both sides. 

Knex introduced code which produced unhandled rejections. That their fault. 

But on feathers side current test system did not catch those rejections, [all was green](https://github.com/feathersjs-ecosystem/feathers-knex/pull/208) and a pull request from greenkeeper was merged. That what should be fixed as unhandled rejections is a serious deal. And it will take only one line in `mocha.opts` to ensure this will not happen latter in knex adapter or any other.

Later on when node will change behaviour and start to crash on unhandled rejections by itself this file and the mocha option can be simply removed.

**Comment by vonagam** [comment]
Changed the script. Now tests will continue to run after an unhandled rejection, but before process exit it will ensure that exit status is non-zero if there were any rejections. I think this is more suitable for tests than abrupt exit as you will be able to see tests results.

**Comment by vonagam** [comment]
Alternative solution is to add [`loud-rejection`](https://github.com/sindresorhus/loud-rejection) to dependencies, then in adapter you use it like `--require loud-rejection/register`. This solution requires no additional file but an additional dependency.

**Comment by vonagam** [comment]
Closing in favour of using `loud-rejection` directly in specific packages.

[Here](https://github.com/feathersjs-ecosystem/feathers-knex/pull/210) is PR for `feathers-knex`.

**Comment by daffl** [comment]
That makes sense, thank you! Since it's only a development dependency I think this is fine.

**Pull request closed without merging**
