### PR TITLE
Add backers & sponsors from Open Collective

### PR DESCRIPTION
**Pull request by piamancini**
This is for your open collective backers and sponsors to appear directly on your readme. 
see how it'll look [here](https://github.com/apex/apex#backers)
[More info](https://github.com/opencollective/opencollective/wiki/Github-banner)

Also add badges on top.

### Summary

(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))

- [ ] Tell us about the problem your pull request is solving.
- [ ] Are there any open issues that are related to this?
- [ ] Is this PR dependent on PRs in other repos?

If so, please mention them to keep the conversations linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).

Thanks for contributing to Feathers! :heart:

### CODE REVIEW

**Comment by ForsakenHarmony** [comment]
what's up with this?

**Comment by daffl** [comment]
Open Collective is up and running but we're still planning on how to announce sponsorship/support models properly.

**Comment by piamancini** [comment]
happy to help if you want to bounce ideas.

**Comment by daffl** [comment]
This has been announced now at https://blog.feathersjs.com/flying-into-2018-13bda623f089 and will be merged.

**Pull request merged**
