### PR TITLE
Correct typings for app.use with both middleware and feathers service.

### PR DESCRIPTION
**Pull request by SteffenLanger**
### Summary

(If you have not already please refer to the contributing guideline as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#pull-requests))

- [x] Tell us about the problem your pull request is solving. - **See https://github.com/feathersjs-ecosystem/feathers-typescript/issues/26#issuecomment-483737013**
- [x] Are there any open issues that are related to this? **Yes: https://github.com/feathersjs-ecosystem/feathers-typescript/issues/26#issuecomment-483737013**
- [x] Is this PR dependent on PRs in other repos? **No.**

If so, please mention them to keep the conversations linked together.

### Other Information

If there's anything else that's important and relevant to your pull
request, mention that information here. This could include
benchmarks, or other information.

Your PR will be reviewed by a core team member and they will work with you to get your changes merged in a timely manner. If merged your PR will automatically be added to the changelog in the next release.

If your changes involve documentation updates please mention that and link the appropriate PR in [feathers-docs](https://github.com/feathersjs/feathers-docs).

Thanks for contributing to Feathers! :heart:

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the PR. I haven't forgotten about this, I'm just not sure I'm following it completely. Wouldn't the `use` signature that we want just be something like

```
use(... args[]: ExpressMiddleware|Service)
```

**Comment by SteffenLanger** [comment]
The idea behind this rather complex structure is this:

- Allow everything express.js allows: `express.IRouterHandler<T> & ((...handlers: RequestHandlerParams[]) => T)`.
- And only allow what express.js expects, for example no request handler with 5 arguments such as `(req, res, next, dummyA, dummyB) => {}`
- Allow everything feathers.js allows: `FeathersRouterMatcher<T>`

The `FeathersRouterMatcher<T>` is so complicated because `app.use()` can work with a path and any of the following in any order:

- express middleware
- feather.js service object
- another application

**Comment by deskoh** [comment]
See [here](https://github.com/feathersjs-ecosystem/feathers-typescript/issues/26) for issue for this type definition.

**Comment by daffl** [comment]
Ok, let's give this a try then. Sorry about the conflict. Would be great if you could resolve it and then we'll get it into the next prerelease.

**Comment by daffl** [comment]
I'm going to close this since it has diverged quite a bit. It would still be nice to get it into the latest master though.

**Pull request closed without merging**
