### PR TITLE
Dynamic services

### PR DESCRIPTION
**Pull request by marshallswain**
Creates the ability to add services at runtime.  This is going to take a bit more effort to test out properly, but I wanted to get it out   in the wild to get some feedback on it while I'm in the process of further testing.  Maybe you'll see something that I haven't noticed, yet.  I'll report back what I find.

### CODE REVIEW

**Comment by marshallswain** [comment]
Oops.  I left that other commit in there.  I'll look into the test for that to see what's going on.

**Comment by marshallswain** [comment]
@daffl can you help me understand what's going on in this test?  There's only one argument passed to Proto.isPrototypeOf().  What is being compared here? https://github.com/feathersjs/feathers/blob/master/test/application.test.js#L47

and also here:
https://github.com/feathersjs/feathers/blob/master/lib/application.js#L32
How/what is Proto extending when there's only one argument?

**Comment by marshallswain** [comment]
Heh.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isPrototypeOf

No matter how much time passes, every day I discover that I'm still an amateur.

**Comment by marshallswain** [comment]
OK.  It looks like that test is failing because when you clone Uberproto it breaks the prototype "link" so that isPrototypeOf no longer works.  
```js

var _ = require('lodash');

// Clone Uberproto
var Proto = _.clone(require('uberproto'));
var dummyService = {
  create: function (data, params, callback) {
    callback(null, data);
  }
};

dummyService = Proto.extend(dummyService);
console.log(Proto.isPrototypeOf(dummyService)); // true

// Clone again and compare
var Proto = _.clone(require('uberproto'));
console.log(Proto.isPrototypeOf(dummyService)); // false

```
That test won't work after cloning Uberproto.

**Comment by marshallswain** [comment]
CRUD tests are passing.  Event-related tests are all failing.

Almost there.

**Comment by marshallswain** [comment]
Victory!  @daffl, we now have dynamic services.  This takes care of #82.

**Comment by marshallswain** [comment]
I just noticed this comment: https://github.com/feathersjs/feathers/issues/67#issuecomment-44757986
>The problem with setting up services right away when calling .use() is that they won't be able to use any other service that has been registered later on.

I added a test for looking up a service added after listen().

**Comment by marshallswain** [comment]
Those last two commits fix #96.  The server will no longer crash when a socket client fails to pass a callback.  It basically creates a dummy callback function that does nothing unless there is an error, in which case it will log the error to the server console.  That should help the developer to not pull as much hair out... if they have access to the server logs.

**Comment by daffl** [comment]
This looks great, thank you! I will have a close look and then merge it. Now I just have to somehow figure out the Proto._create problem. But that should be solvable.

**Comment by marshallswain** [comment]
Here's another attempt at a fix that actually passes all of the tests.  I put a custom version of uberproto.js in the libs directory and have replaced all require() references with a reference to the custom one.

**Comment by marshallswain** [comment]
I just don't know what effect this will have on feathers-[service] modules, yet.

**Comment by marshallswain** [comment]
I simplified the file by removing the extra factory function, et al.  Other than that, I renamed the create to _create and added a comment to the top... and a JSHint directive to ignore making functions inside loops.

I did some testing.  If you make two **completely identical** copies of uberproto.js and extend an object with one, the extended object knows its parent. (Mommy issues or something, I guess.)
```js
var Proto = require('./uberproto');
var proto = require('uberproto');
var cage = {
  animal: 'moose'
};
var moose = Proto.extend(cage);
console.log(proto.isPrototypeOf(moose)); // false
console.log(Proto.isPrototypeOf(moose)); // true
```
Maybe it tracks the register in memory that contains the original?  I don't remember.  Anyway, other services will have to figure out a solution... unless we put a uberproto-feathers module in NPM.  It shouldn't be much of an issue, other than in tests.  Actually, to solve that and maybe improve the quality of custom feathers services, maybe we could put the tests in their own NPM module.  We could then create an NPM module that's ready to test.

**Comment by marshallswain** [comment]
Woot!  I'm on the team!  

Ok.  I'm super tempted to merge this, but for the sake of checks and balances, I'd prefer that somebody else does it.

**Comment by daffl** [comment]
Actually first, could you push to a branch on this repository so that I can check it out?

**Comment by marshallswain** [comment]
Done.  https://github.com/feathersjs/feathers/tree/dynamic-services

**Comment by ekryski** [comment]
@marshallswain :boom: nice work man. That is suweet!

**Comment by ekryski** [comment]
@daffl and I have been talking about creating a test harness for the crud adapters for a while. I'll cook something up this week. I have a bit more free time now.

**Comment by daffl** [comment]
I didn't forget about this just didn't have the time to go over everything yet, sorry.

**Comment by daffl** [comment]
Allright, I think #104 and #105 should make for a new patch release which I think also caused some issues in this PR. @marshallswain Could you clean this one up one more time when those are in?

I think it looks good besides that but maybe we can discuss if there is a way to consolidate functionality even more.

**Comment by marshallswain** [comment]
@daffl @ekryski Done.  I've created a cleaner PR for dynamic services in #107.

**Pull request closed without merging**
