### PR TITLE
fix(authentication): Include query params when authenticating via authenticate hook

### LINKED ISSUE #2007: Issue authenticating user via JWT when users service requires query params
### Copied from Slack Convo
the authenticate hook cannot function as is when the db requires query params to correctly lookup the user entity during authentication, which is a common case for hosted mongodb databases which require a shard-key (specifically when using Azure CosmosDB)

### Expected
Using `authenticate("JWT")` hook successfully authenticates user.

### Actual
Authenticate hook fails with db error, `No record found for id ***`.

### PR DESCRIPTION
**Pull request by flyboarder**
Supersedes #2008 fixes #2007

### CODE REVIEW

**Comment by daffl** [comment]
Looks like nothing is breaking and I reviewed the dependent calls and there really appears no reason anymore for not including the query.

**Comment by DevBayer** [comment]
It seems to me that something is failing in his logic, including the query parameter is breaking my code, I use the authenticate('jwt') hook as a header everywhere and is performing the query to the service by adding in the query a column that obviously does not exist in the users model because the main query is directed on another service that uses another object model.

**Comment by jchamb** [comment]
@daffl @DevBayer Same thing for me. letting the query param through basically  broke every request in my app, as it was trying to attach extra fields into the user query

**Comment by daffl** [comment]
Not sure how i missed that, that's exactly what I was worried about. Fixed in v4.5.6.

**Comment by flyboarder** [comment]
@daffl Would you like to review #2008 as a possible alternative solution?

**Comment by jchamb** [comment]
Do most of the adapters support pulling the model attributes like sequelize? It would be pretty easy to apply a whitelist of allowed fields by just pulling the models attributes.

**Comment by flyboarder** [comment]
@jchamb that would assume the user service is backed by a database adapter, and not for example a proxy to another service.

**Comment by jchamb** [comment]
@flyboarder very true. Was just thinking as an easy default whitelist for what is prob the more common/standard installs. I would say that, that would also be an easy config, but if your going to have to config something might as well just make be explicit like your #2008

**Pull request merged**
