### PR TITLE
Open hook workflow to custom methods

### PR DESCRIPTION
**Pull request by bertho-zero**
**Works with https://github.com/feathersjs/commons/pull/72.**

This PR allows you to add converters to your custom methods, which allows to create the hook corresponding to your arguments and finally to fully use the hook workflow.

I would have liked to use a Symbol but https://github.com/feathersjs/feathers/issues/863.

Example:
```js
const app = feathers().use('/dummy', {
  methods: {
    custom: ['id', 'data', 'params']
  },
  get() {},
  // ...
  custom(id, data, params) {
    return Promise.resolve([id, data, params]);
  }
});

app.service('dummy').hooks({
  before: {
    all: [/**/],
    custom: [/**/]
  },
  after: {
    all: [/**/],
    custom: [/**/]
  }
});

app.service('dummy').custom(28, { bar: 'foo' }, { provider: 'rest' });
```

### CODE REVIEW

**Comment by bertho-zero** [comment]
And then we can take advantage of authentication, validation, formatting, parsing, etc. without any other effort:

```js
// for async/await in express middleware
const wrap = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);

app.use('/custom', wrap(async (req, res) => {
  const result = await app.service('dummy')
    .custom(1, req.body, {
      query: req.query,
      provider: 'rest'
    });
  res.send({ result });
}));
```

**Comment by bertho-zero** [comment]
I just thought of another syntax:
```js
const app = feathers().use('/dummy', {
  get() {},
  // ...
  @enableHooks(['id', 'data', 'params'])
  custom(id, data, params) {
    return Promise.resolve([id, data, params]);
  }
});

// or without decorator

const app = feathers().use('/dummy', {
  get() {},
  // ...
  custom: enableHooks(['id', 'data', 'params'])(
    (id, data, params) => {
      return Promise.resolve([id, data, params]);
    }
  )
});

```

Which do you prefer between this one and that of the PR?

**Comment by bertho-zero** [comment]
I think that all methods can be added to `service.methods`, for example the argument list can be used in `@feathersjs/express` to convert the request into arguments.

https://github.com/feathersjs/express/blob/9bc5541107bfd1ec58d3e38fb968b91832cda377/lib/rest/wrappers.js#L111-L116

**Comment by daffl** [comment]
I like the

```js
const app = feathers().use('/dummy', {
  get() {},
  // ...
  custom: activateHooks(['id', 'data', 'params'])(
    (id, data, params) => {
      return Promise.resolve([id, data, params]);
    }
  )
});
```

Syntax. Now that you got Symbols working, is there anything that would change?

**Comment by bertho-zero** [comment]
I just had to rename `activeHooks` to `activateHooks`, it's all good.
Just publish a version with the latest `@feathers/commons` changes and tests pass.

**Comment by bertho-zero** [comment]
`@feathersjs/express` for example, could use a function like 
```js
function makeArgsGetter (argsOrder) {
  return (req, params) => argsOrder.reduce((result, argName) => {
    switch (argName) {
      case 'id':
        return [ ...result, req.params.__feathersId || null ];
      case 'data':
        return [ ...result, req.body ];
      case 'params':
        return [ ...result, params ];
    }
  }, []);
}
```
and `argsOrder` comes from `service.methods` or `Symbol`.

Using the Symbols implies that you need a require of `@feathersjs/feathers` to compare with the original Symbol, perhaps an https://docs.npmjs.com/files/package.json#optionaldependencies.
Symbols can only be used in `@feathersjs/feathersjs` if you pass all methods by `service.methods` (not just customs)

**Comment by daffl** [comment]
I'll review this again over the weekend. The problem with Symbols is that they may not work in the browser (although I _think_ that the Polyfill Feathers requires should work for most).

**Comment by bertho-zero** [comment]
Thank you. Symbols have polyfills and feathers no longer explicitly require babel-polyfill but we can put a note for those who want to use this feature.

Symbols are not compatible with all browsers, be sure to precompile your code or add a Polyfill for older browsers.
In other cases your services will have a `__feathersActivateHooks` property.

**Comment by bertho-zero** [comment]
Perhaps you could release a major beta version of `@feathersjs/common` and a version of `@feathersjs/feathers` on a tag that is not "latest" ? It will allow to test that in production.

This change is a new feature without regression or change of API, it could even be published in a patch version without waiting for the Crow version.

**Comment by daffl** [comment]
You are totally right. Sorry I'm so slow - that happens with me sometimes during summertime 😉 - I just released a version 2.0.0 of https://github.com/feathersjs/commons. Could you update the pull request pointing to that version and fix the conflicts? Then everything should pass right? How does #875 fit in here?

**Comment by bertho-zero** [comment]
#875 is apart, I'll update it after.

**Comment by daffl** [comment]
They should go out in the same version though right?

**Comment by bertho-zero** [comment]
Not necessarily, It can go out in another version.
I'll update it next week.

**Pull request closed without merging**
