### PR TITLE
fix(adapter-commons): faster sorter

### PR DESCRIPTION
**Pull request by fratzinger**
This is a small refactoring.

- check for 'null && undefined' in one if
- detect typeof only once
- move get fn outside
- check key.includes('.') before key.split('.')
- type compareNSB & compareString

### CODE REVIEW

**Review by daffl — APPROVED** [review]

**Comment by daffl** [comment]
This looks good, thank you. I wonder if there is a more generic package for this kind of thing. Doesn't seem to be something we should have to maintain ourselves - I took this from NeDB when it stopped being maintained.

**Comment by fratzinger** [comment]
https://github.com/kofrasa/mingo could help. But I think it's fine. It's a small utility which is not a subject of change often and most adapters use `@feathersjs/adapter-commons` for other reasons anyways. It's good to have it in this package. 

I think we should not overcomplicate this. Or we end up importing and exporting from another library and their versioning has to align with our versioning. We have enough of these problems.

**Comment by daffl** [comment]
True. It might be worth getting more test coverage for it eventually if we do want to keep it around.

**Comment by fratzinger** [comment]
💯. I also thought about that.

**Pull request merged**
