### PR TITLE
Typings fix and improvements.

### PR DESCRIPTION
**Pull request by deskoh**
1. Fixed typings for Service.

```
- service<L extends keyof ServiceTypes> (location: L): ServiceTypes[L];
+ service<L extends keyof ServiceTypes> (location: L): Service<ServiceTypes[L]>;
```

2. Improvement in service typings is described as follows.

Current typings consists of a catch-all for any service name:

```TypeScript
export interface Application<ServiceTypes = any> extends EventEmitter {

    service<L extends keyof ServiceTypes> (location: L): Service<ServiceTypes[L]>;

    // vvv: Catch-all for any service name
    service (location: string): Service<any>;
}

```

This allows service type to resolve if no `ServiceType` is specified.

```TypeScript
const app = feathersExpress(feathers());
let service1 = app.service('messages'); // service1: Service<any>
```

However, if `ServiceType` is specified, invalid service name should not be resolved:

```TypeScript
type Message = { text: string };
type App = Application<{ messages: Message }>;

const app2 = feathersExpress(feathers()) as App;
let service3 = app2.service('messages'); // service3: Service<Message>
let service4 = app2.service('message');  // service4: never <- Will resolve to Service<any> for current typings
```

Defaulting the `ServiceType` to `never` and modifying the 'catch-all' typings can fulfill the above:

```TypeScript
export interface Application<ServiceTypes = never> extends EventEmitter {

    service<L extends keyof ServiceTypes> (location: L): Service<ServiceTypes[L]>;

    // vvv: Modified catch-all for service name if `ServiceType` is not provided,
    // Array type somehow is required for conditional type to work correctly for never
    service (location: string): [ServiceTypes] extends [never] ? Service<any> : never;
}
```

### CODE REVIEW

**Comment by deskoh** [comment]
Expected type resolution:

```TypeScript
let app: Application<{ users: User }>;
app.service('users'); // Service<User>
app.service('user');  // never

let app2: Application<any>;
app2.service('users'); // Service<any>
app2.service('user');  // Service<any>

let app3 = Application; // equivalent to Application<never>
app3.service('users'); // Service<any>
app3.service('user');  // Service<any>
```

**Comment by deskoh** [comment]
Test seems to fail due to the fix below:

```Typescript
-        service<L extends keyof ServiceTypes> (location: L): ServiceTypes[L];
+        service<L extends keyof ServiceTypes> (location: L): Service<ServiceTypes[L]>;
```

**Comment by daffl** [comment]
Thank you for the pull request. If someone just uses `const app: Application` without specifying the services mappings, it would still work (it'll just be returned as `any`) right?

**Comment by deskoh** [comment]
Yeap.

**Comment by daffl** [comment]
Great. Thanks again!

**Pull request merged**
