### PR TITLE
feat(authentication-oauth): Set oAuth redirect URL dynamically

### PR DESCRIPTION
**Pull request by fadiquader**
### Summary
Referred to this bug https://github.com/feathersjs/feathers/issues/1591 
Fixed set oauth redirect URL dynamically.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you! I updated the PR with a test and changed it to pass all of `params` to the `getRedirect` method.

The default oAuth strategy now also includes the original `redirect` setting. So a query redirect like `?redirect=/dashboard` with a `oauth.redirect` option of `https://app.mydomain.com` will redirect to `https://app.mydomain.com/dashboard`. The redirect can't be a generic URL, otherwise an attacker could steal a token by sending a link that redirects to their URL.

**Comment by elv1n** [comment]
@daffl Redirect only works when `featers_token` provided to link accounts. It will be extremely useful to have a query in session to manipulate with it in `getRedirect` fn.
Are there any downsides to have the feature?

**Comment by daffl** [comment]
Are you sure? This should work whenever the `?redirect=` query parameter is set during oAuth login.

**Comment by elv1n** [comment]
Sorry, if I missed something
Here is a skip part
```
 if (feathers_token) {
        debug(`Got feathers_token query parameter to link accounts`, feathers_token);
        req.session.accessToken = feathers_token;
        req.session.query = query;
      }
```
and then it takes from session on authenticate route
```
 authApp.get('/:name/authenticate', async (req, res, next) => {
      const { name } = req.params as any;
      const { accessToken, grant, query = {} } = req.session;
```

**Comment by daffl** [comment]
Dang, you're totally right, that should definitely live outside of that statement. PR would be welcome.

**Pull request merged**
