### PR TITLE
Added generators for feathers-objection & feathers-cassandra

### PR DESCRIPTION
**Pull request by dekelev**

### CODE REVIEW

**Comment by daffl** [comment]
This is great, thank you! I'll have a look at it on the weekend.

In order to keep them as official adapters in the future, do you plan on including the changes coming in https://github.com/feathersjs/feathers/issues/925?

**Comment by dekelev** [comment]
Sure, these changes makes a lot of sense.

`feathers-objection` allows eager queries, like mongoose's $populate, but for example, `allowedEager: 'todos'` in the `users` service options acts as the whitelist and will only allow getting `user.todos`, using `query.$eager = 'todos'`.
`allowedEager: '[todos, account]'` will also allow getting the `account` relation.

`feathers-objection` also has `Upsert/Insert` feature, which will update relations too. this requires the `allowedUpsert`, `allowedInsert` and `createUseUpsertGraph` service options.

`feathers-cassandra` doesn't support relations, so I can't think of anything there that needs whitelisting.

Both packages should already respect the `query` object in `get`, `remove`, `update` and `patch`, but I'll test this to verify.

I'll add support & docs for the `multi` service option in both projects.

Let me know if you can think of anything else. enjoy your weekend!

**Comment by daffl** [comment]
I'll keep you in the loop what the plan is with those updates and will try to get your PR in soon.

**Comment by daffl** [comment]
Released in `@feathersjs/cli@3.8.5`

**Pull request merged**
