### PR TITLE
express: use service.methods

### PR DESCRIPTION
**Pull request by bertho-zero**
Apply feathersjs/express#29 `.diff`

### CODE REVIEW

**Comment by bertho-zero** [comment]
@daffl I resolved the conflict with master.

**Comment by bertho-zero** [comment]
@daffl I merged master and all the tests seem to pass.

**Comment by daffl** [comment]
So the difficulty with this one is that we can't force the dependent Feathers version unless it is a major (breaking) change. If someone has e.g. `@feathersjs/feathers@3.1.x` things will break (already seeing some issues around that, e.g. in #1000).

**Comment by bertho-zero** [comment]
`@feathersjs/express` probably requires a major version.

**Comment by daffl** [comment]
I think so, too. Ok, I'll get this in with auth v3 (since authentication Express middleware will move here, too). It's going pretty well so it hopefully shouldn't be too long until a pre-release.

**Comment by Mairu** [comment]
Please don't forget this for 4.0

**Pull request merged**
