### PR TITLE
Enable refresh-token server side support

### PR DESCRIPTION
**Pull request by jackywxd**
### Summary

Enable refresh-token server side support by extending the existing Authentication Service. As refresh-token is a stateful resource, it also depends on refresh-token entity service, similar as local strategy depends on user entity service.

Related issue: #1337 

Includes unit test cases

### CODE REVIEW

**Comment by daffl** [comment]
Thank you very much for this pull request @jackywxd! Sorry it took so long to get back to it. I think this is a great start. My questions would be

- If it can be its own module, it is always easier to publish it separately instead of pulling it into the core
- Aren't there any changes that need to be made in the core modules (like the `authentication-client`)?

**Comment by jackywxd** [comment]
@daffl David, thanks for your time! You are right, it can be on its own module and it is a much cleaner and easier solution. 

The current code change is only applied for server-side, not related to `authentication-client`. I have't got a chance to look at the client-side code yet. Ideally, the client-side integration should be included. 

Anyway, I will close this request for now, will see if I can make changes to both server and client and publish as separated modules.

Thanks again!

**Comment by daffl** [comment]
Great, thank you. Please let me know if you need anything. Once it is ready we should definitely also do a writeup.

**Comment by itoonx** [comment]
I'm looking for it 👍

**Comment by bujji1** [comment]
@jackywxd!  I found only the TypeScript version of the "refresh token "  fork , do we have the Java script version also? Thanks for your help on this.

**Pull request closed without merging**
